export const GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST';
export const GET_TOTAL_CATEGORIES = 'GET_TOTAL_CATEGORIES';
export const CHANGE_QUERY_INFO = 'CHANGE_QUERY_INFO';
export const ADD_CATE_VISABLE = 'ADD_CATE_VISABLE';
export const GET_PARENT_CATE_LIST = 'GET_PARENT_CATE_LIST';