export const CHANGE_USER_LIST = ' CHANGE_USER_LIST';
export const CHANGE_TOTAL = 'CHANGE_TOTAL';
export const CHANGE_QUERY_INFO = 'CHANGE_QUERY_INFO';
export const CHANGE_ADD_USER_MODAL_VISABLE = 'CHANGE_ADD_USER_MODAL_VISABLE';
export const GET_ROLE_LIST = 'GET_ROLE_LIST';